CC2021/CC2021Proyecto/Controllers/OrdenDeProduccionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Specifications;
using CC2021Proyecto.ViewModels;
using Datos.Data.Interfaces;
using Dominio.Entities;
using Dominio.Entities.Enums;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CC2021Proyecto.Controllers
{
    public class OrdenDeProduccionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrdenDeProduccionController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> ObtenerLineas()
        {
            var spec = new AddOrdersIncludesSpecification();
            var ordenes = await _unitOfWork.Repository<OrdenDeProduccion>().ListAsync(spec);

            return View(ordenes);
        }


        public async Task<IActionResult> IniciarNuevaOrden()
        {
            var colores = await _unitOfWork.Repository<Color>().ListAllAsync();
            var modelos = await _unitOfWork.Repository<Modelo>().ListAllAsync();
            var specLineas = new AddLineasIncludesSpecification();
            var lineas = await _unitOfWork.Repository<LineaDeTrabajo>().ListAsync(specLineas);
            var estadoFinalizada = EstadoOrden.Finalizada;
            var lineasDisponibles = new List<LineaDeTrabajo>();

            
                foreach (var linea in lineas)
                {
                    var validado = linea.ObtenerLineaSiEstaFinalizada(estadoFinalizada);
                    if (validado)
                    {
                        lineasDisponibles.Add(linea);
                    }
                }
                var OrdenIniciarViewModel = new OrdenIniciarViewModel
                {
                Colores = colores,
                Lineas = lineasDisponibles,
                Modelos = modelos,
                Coloress = colores,
                Modeloss=modelos,
                Lineass= lineasDisponibles
                };

                return View(OrdenIniciarViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CrearOrden(OrdenIniciarViewModel orden, int numeroOrden)
        {
            var usuario = await ObtenerUsuario();

            var specLinea = new LineaConIdSpecification(Int32.Parse(orden.LineaSelected));
            var linea = await _unitOfWork.Repository<LineaDeTrabajo>().GetEntityWithSpec(specLinea);

            var specModelo = new ModeloConNumeroSpecification(orden.ModeloSelected);
            var modelo = await _unitOfWork.Repository<Modelo>().GetEntityWithSpec(specModelo);

            var specColor = new ColorConNumeroSpecification(Int32.Parse(orden.ColorSelected));
            var color = await _unitOfWork.Repository<Color>().GetEntityWithSpec(specColor);

            var turnos = await _unitOfWork.Repository<Turno>().ListAllAsync();
            var horaActual =  _unitOfWork.GetHora();

            var estadoFinalizada = EstadoOrden.Finalizada;

            var specLineas = new AddLineasIncludesSpecification();
            var lineas = await _unitOfWork.Repository<LineaDeTrabajo>().ListAsync(specLineas);

            int usuarioValidado = 0;

            if (ModelState.IsValid)
            {
                foreach (var li in lineas)
                {
                    var validacionDeEmpleado = li.ComprobarAsignacionSupervisor(usuario.Empleado);
                    if (validacionDeEmpleado)
                    {
                        usuarioValidado++;
                    }
                }

                if (linea != null && modelo != null && color != null && usuario != null && usuarioValidado==lineas.Count)
                {
                    var lineaDisponible = linea.ObtenerLineaSiEstaFinalizada(estadoFinalizada);
                    if (lineaDisponible)
                    {
                        var spec = new OrdenConNumeroSpecification(numeroOrden);
                        var ordenExistente = await _unitOfWork.Repository<OrdenDeProduccion>()
                            .GetEntityWithSpec(spec);
                        if (ordenExistente == null)
                        {
                            var ordenV =
                                linea.CrearOrden(numeroOrden, modelo, color, usuario.Empleado, turnos, horaActual);
                            if (ordenV != null)
                            {
                                _unitOfWork.Repository<LineaDeTrabajo>().Update(linea);
                                await _unitOfWork.Complete();
                            }
                            ModelState.AddModelError("","Se debe crear la orden en un turno valido ");
                        }
                        ModelState.AddModelError("", "Orden ya existente, ingrese otra");
                    }
                    ModelState.AddModelError("", "Orden activa en linea" + linea.Numero + ", finalice la ultima para crear otra");
                }
            }
           
            return RedirectToAction("ObtenerLineas");
        }

        private async Task<Usuario> ObtenerUsuario()
        {
            var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            var specUsuario = new ValidarEmpleadoSpecification(sessionUser.User);
            var usuario = await _unitOfWork.Repository<Usuario>().GetEntityWithSpec(specUsuario);

            return usuario;
        }

        [HttpPost]
        public async Task<IActionResult> PausarOrden(int numeroLinea)
        {
            var usuario = await ObtenerUsuario();

            if (usuario != null)
            {
                var specLinea = new LineaConNumeroYEmpleadoSpecification(numeroLinea, usuario.Empleado);
                var lineaValida = await _unitOfWork.Repository<LineaDeTrabajo>().GetEntityWithSpec(specLinea);

                if (lineaValida != null)
                {
                    var specOrden = new OrdenConEstadoABuscarSpecification(lineaValida, EstadoOrden.Activa);
                    var ordenActiva = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

                    var horaActual = _unitOfWork.GetHora();

                    if (ordenActiva != null)
                    {
                        lineaValida.PausarOrden(horaActual, ordenActiva);
                        await _unitOfWork.Complete();
                    }
                }
            }
            return RedirectToAction("ObtenerLineas");
        }

        public async Task<IActionResult> ReanudarOrden(int numeroLinea)
        {
            var usuario = await ObtenerUsuario();

            if (usuario != null)
            {
                var specLinea = new LineaConNumeroYEmpleadoSpecification(numeroLinea, usuario.Empleado);
                var lineaValida = await _unitOfWork.Repository<LineaDeTrabajo>().GetEntityWithSpec(specLinea);

                if (lineaValida != null)
                {
                    var specOrden = new OrdenConEstadoABuscarSpecification(lineaValida, EstadoOrden.Pausada);
                    var ordenActiva = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

                    var horaActual = _unitOfWork.GetHora();
                    var turnos = await _unitOfWork.Repository<Turno>().ListAllAsync();


                    if (ordenActiva != null && turnos != null && usuario != null)
                    {
                        lineaValida.ReanudarOrden(turnos, horaActual, ordenActiva);
                        await _unitOfWork.Complete();
                    }
                }
            }
            return RedirectToAction("ObtenerLineas");
        }

        public async Task<IActionResult> FinalizarOrden(int numeroLinea)
        {
            var usuario = await ObtenerUsuario();

            if (usuario != null)
            {
                var specLinea = new LineaConNumeroYEmpleadoSpecification(numeroLinea, usuario.Empleado);
                var lineaValida = await _unitOfWork.Repository<LineaDeTrabajo>().GetEntityWithSpec(specLinea);
                if (lineaValida != null)
                {
                    var specOrden = new OrdenesConOrdenActivaYPausadaConLineaSpecification(lineaValida);
                    var ordenActivaOPausada = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

                    var horaActual = _unitOfWork.GetHora();

                    if (ordenActivaOPausada != null)
                    {
                        lineaValida.FinalizarOrden(horaActual, ordenActivaOPausada);
                        await _unitOfWork.Complete();
                    }
                    ModelState.AddModelError("","Orden ya finalizada");
                }
            }

            return RedirectToAction("ObtenerLineas");
        }
    }
}

CC2021/CC2021Proyecto/Views/OrdenDeProduccion/IniciarNuevaOrden.cshtml
@using System.Linq.Expressions
@using Dominio.Entities
@model OrdenIniciarViewModel
<!--App-->
<div class="d-flex flex-column justify-content-center w-100 my-4">
    <div class="container">

        @using (Html.BeginForm("CrearOrden", "OrdenDeProduccion", FormMethod.Post, new
        {
            @class = "form-group d-flex align-items-center justify-content-center "
        }))
        {
            <div asp-validation-summary="All"></div>
            <div class="container border border-primary align-items-center p-4 my-4">
                <div class="container mx-auto w-50">
                    <label style="color: floralwhite" for="">Numero de orden:</label>
                    <input name="numeroOrden" id="numeroOrden" class="form-control" type="text">
                </div>
                <div class="container w-50 justify-content-center my-4">
                    <div >
                        <div class="" style="display: flex; justify-content:space-between;">
                            <div class="dropdown" >
                                @Html.DropDownListFor(x => x.ColorSelected, new SelectList(Model.Coloress, "Codigo", "Descripcion"), "Color", htmlAttributes: new
                                {
                                    @class = "btn btn - primary dropdown - toggle" ,
                                    @style = "color: floralwhite"
                                })
                                @for (int i = 0; i < Model.Coloress.Count; i++)
                                {
                                    <input type="hidden" name="@Model.Coloress[i].Descripcion" value="@Model.Coloress[i].Descripcion" />
                                    <span asp-validation-for="@Model.Coloress[i].Descripcion" class="danger"></span>

                                }
                            </div>
                            <div class="dropdown">
                                @Html.DropDownListFor(x => x.ModeloSelected, new SelectList(Model.Modeloss, "Sku", "Denominacion"), "Modelo", htmlAttributes: new { @class = "btn btn - primary dropdown - toggle",
                               @style = "color: floralwhite"
                           })
                                @for (int i = 0; i < Model.Modeloss.Count; i++)
                                {
                                    <input type="hidden" name="@Model.Modeloss[i].Denominacion" value="@Model.Modeloss[i].Denominacion" />
                                    <span asp-validation-for="@Model.Modeloss[i].Denominacion" class="danger"></span>

                                }

                            </div>

                            <div class="dropdown">
                                @Html.DropDownListFor(x => x.LineaSelected, new SelectList(Model.Lineass, "Id", "Numero"), "Linea", htmlAttributes: new { @class = "btn btn - primary dropdown - toggle",
                               @style = "color: floralwhite"
                           })
                                @for (int i = 0; i < Model.Lineass.Count; i++)
                                {
                                    <input type="hidden" name="@Model.Lineass[i].Numero" value="@Model.Lineass[i].Numero" />
                                    <span asp-validation-for="@Model.Lineass[i].Numero" class="danger"></span>

                                }
                            </div>
                        </div>

                    </div>
                </div>
                <div class="d-flex">
                    <button type="submit" value="submit" class='btn btn-primary btn-sm' style="width: 10vw;">Crear</button>
                    <button asp-controller="OrdenDeProduccion"
                            asp-action="ObtenerLineas"class='btn btn-primary btn-sm ml-auto' style="width: 10vw;">Salir</button>
                </div>
            </div>
            

        }
    </div>
</div>

CC2021/CC2021Proyecto/Views/OrdenDeProduccion/ObtenerLineas.cshtml
@using Dominio.Entities.Enums
@model IReadOnlyList<Dominio.Entities.OrdenDeProduccion>
<!--App-->
    <div class="container text-center" >
        <h2 class='my-4' style="color: floralwhite">Administrar ordenes de produccion</h2>
        <div class="d-flex flex-column my-2">
            <div class="d-flex justify-content-start mb-2">
                <a asp-controller="OrdenDeProduccion" asp-action="IniciarNuevaOrden"><button class="btn btn-primary">Iniciar orden de produccion</button></a>
            </div>
            <!--<div class="container border border-primary overflow-auto" style="height: 60vh; width: 100vw">-->
            <table class="table table-striped" style="color: floralwhite">
                <thead>
                    <tr>
                        <th scope="col">Numero de linea</th>
                        <th scope="col">Numero de orden</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Color</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Supervisor Linea</th>
                        <th scope="col">Supervisor calidad </th>
                        <th scope="col">Reanudar</th>
                        <th scope="col">Pausar</th>
                        <th scope="col">Finalizar</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var orden in @Model)
                    {
                        if (@Model.Count > 0)
                        {
                    <tr>
                        <th scope="row">@orden.Linea.Numero</th>
                        <td>@orden.Numero</td>
                        <td>@orden.Modelo.Denominacion</td>
                        <td>@orden.Color.Descripcion</td>
                        <td>@orden.Estado</td>
                        <td>@orden.LineaIniciadaPor.Nombre @orden.LineaIniciadaPor.Apellido</td>
                        @if (orden.EmpleadoOrden == null)
                        {
                            <td>No asignado</td>
                        }
                        else
                        {
                            <td>@orden.EmpleadoOrden.Nombre @orden.EmpleadoOrden.Apellido</td>
                        }
                        
                        <td>
                            <form asp-controller="OrdenDeProduccion"
                                  asp-action="ReanudarOrden"
                                  asp-route-numeroLinea="@orden.Linea.Numero"
                                  method="post">
                                <button disabled="@(EstadoOrden.Activa == orden.Estado ? "disabled" : null)"
                                        class="btn btn-success btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-play-btn" viewBox="0 0 16 16">
                                        <path d="M6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814l-3.5-2.5z" />
                                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm15 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                        <td>
                            <form asp-controller="OrdenDeProduccion"
                                  asp-action="PausarOrden"
                                  asp-route-numeroLinea="@orden.Linea.Numero"
                                  method="post">
                                <button disabled="@(EstadoOrden.Pausada == orden.Estado ? "disabled" : null)" class="btn btn-warning btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pause-btn" viewBox="0 0 16 16">
                                        <path d="M6.25 5C5.56 5 5 5.56 5 6.25v3.5a1.25 1.25 0 1 0 2.5 0v-3.5C7.5 5.56 6.94 5 6.25 5zm3.5 0c-.69 0-1.25.56-1.25 1.25v3.5a1.25 1.25 0 1 0 2.5 0v-3.5C11 5.56 10.44 5 9.75 5z" />
                                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm15 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                        <td>
                            <form asp-controller="OrdenDeProduccion"
                                  asp-action="FinalizarOrden"
                                  asp-route-numeroLinea="@orden.Linea.Numero"
                                  method="post">
                                <button disabled="@(EstadoOrden.Finalizada == orden.Estado ? "disabled" : null)"
                                        class="btn btn-danger btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stop-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                        <path d="M5 6.5A1.5 1.5 0 0 1 6.5 5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3z" />
                                    </svg>
                                </button>

                            </form>
                        </td>
                    </tr>
                        }
                    }
                </tbody>
            </table>
            <!--</div>-->
        </div>
    </div>