CC2021/CC2021Proyecto/Controllers/AsociarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using API.Specifications;
using Dominio.Entities;
using Dominio.Entities.Enums;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CC2021Proyecto.Controllers
{
    public class AsociarController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AsociarController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> IniciarAsociacion()
        {
            var spec = new OrdenesConOrdenActivaYPausadaSpecification();
            var ordenes = await _unitOfWork.Repository<OrdenDeProduccion>().ListAsync(spec);

            if (ordenes != null)
            {
                return View(ordenes);
            }

            return View();
        }

        public async Task<IActionResult> AsociarSupervisor(int numeroOrden)
        {

            var usuario = await ObtenerUsuario();

            var specOrden = new OrdenConEstadoActivaOPausadaYNumero(numeroOrden);
            var orden = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

            var specLineas = new AddLineasIncludesSpecification();
            var lineas = await _unitOfWork.Repository<LineaDeTrabajo>().ListAsync(specLineas);

            var supervisorValido = 0;
            var hayActivasOPausadas = 0;

            if (orden != null && usuario.Empleado != null && lineas != null)
            {
                foreach (var linea in lineas)
                {
                    if (linea.OrdenesDeProduccion.All(o => o.Estado == EstadoOrden.Finalizada)) {}
                    else
                    {
                        hayActivasOPausadas++;
                        var supervisorDispo = linea.ValidarSupervisor(usuario.Empleado);
                        if (supervisorDispo)
                        {
                            supervisorValido++;
                        }
                    }
                    
                }

                if (supervisorValido == hayActivasOPausadas)
                {
                    orden.AsociarSupervisor(usuario.Empleado);
                    await _unitOfWork.Complete();
                }
            }

            return RedirectToAction("IniciarAsociacion");
        }
        public async Task<IActionResult> DesasociarSupervisor(int numeroOrden)
        {
            var usuario = await ObtenerUsuario();

            var specOrden = new OrdenConEstadoActivaOPausadaYNumero(numeroOrden);
            var orden = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);


            if (orden != null && usuario.Empleado != null )
            {
                orden.DesasociarSupervisor(usuario.Empleado);
                await _unitOfWork.Complete();
                
            }
            return RedirectToAction("IniciarAsociacion");
        }
        private async Task<Usuario> ObtenerUsuario()
        {
            var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            var specUsuario = new ValidarEmpleadoSpecification(sessionUser.User);
            var usuario = await _unitOfWork.Repository<Usuario>().GetEntityWithSpec(specUsuario);

            return usuario;
        }
    }
}

CC2021/CC2021Proyecto/Controllers/ControlCalidadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Specifications;
using CC2021Proyecto.ViewModels;
using Datos.Data.Interfaces;
using Dominio.Entities;
using Dominio.Entities.Enums;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CC2021Proyecto.Controllers
{
    public class ControlCalidadController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public ControlCalidadController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> IniciarInspeccion(int numeroOrden)
        {
           return await Iniciar(numeroOrden);
        }

        public async Task<IActionResult> Iniciar(int numeroOrden, Defecto defectoSeleccionado= null)
        {
            var usuario = await ObtenerUsuario();

            var specOrden = new OrdenConNumeroSpecification(numeroOrden);
            var ordenCorrecta = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

            if (ordenCorrecta != null)
            {
                var empleadoValido = ordenCorrecta.VerificarAsosiacion(usuario.Empleado);

                if (empleadoValido)
                {
                    var specObservados = new DefectosObservadosSpecification(TipoDefecto.Observado);
                    var specReproceso = new DefectosObservadosSpecification(TipoDefecto.Reproceso);

                    var defectosObservados = await _unitOfWork.Repository<Defecto>().ListAsync(specObservados);
                    var defectosReproceso = await _unitOfWork.Repository<Defecto>().ListAsync(specReproceso);

                    var hora = _unitOfWork.GetHora();

                    var turnos = await _unitOfWork.Repository<Turno>().ListAllAsync();
                    var turno = ordenCorrecta.Linea.ValidarTurno(turnos, hora);


                   // if (turno != null)
                    //{
                        var specHorarios = new HorariosDeOrdenSpecification(ordenCorrecta.Id);
                        var horarios = await _unitOfWork.Repository<HorarioTrabajo>().ListAsync(specHorarios);

                        var defectosListViewModel = new DefectosListViewModel
                        {
                            DefectosObservados = defectosObservados,
                            DefectosReprocesos = defectosReproceso,
                            Hora = hora,
                            Orden = ordenCorrecta,
                            Turno = turno,
                            Hallazgos = ordenCorrecta.Horarios.Last().Hallazgos,
                            Primeras = ordenCorrecta.Horarios.Last().ParesPrimera
                        };

                        if (defectoSeleccionado != null)
                        {
                            defectosListViewModel.def = defectoSeleccionado;
                        }


                        if (horarios.Count > 0)
                        {
                            defectosListViewModel.CantidadPrimera = horarios.Last().ParesPrimera.Count; ;
                        }
                        
                        return View("IniciarInspeccion", defectosListViewModel);
                   // }
                   // else
                   // {
                   //     return RedirectToAction("IniciarAsociacion", "Asociar");
                   // }
                }
            }
            return RedirectToAction("IniciarAsociacion","Asociar");
        }
        private async Task<Usuario> ObtenerUsuario()
        {
            var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            var specUsuario = new ValidarEmpleadoSpecification(sessionUser.User);
            var usuario = await _unitOfWork.Repository<Usuario>().GetEntityWithSpec(specUsuario);

            return usuario;
        }

        public async Task<IActionResult> AgregarParDePrimera(int numeroOrden)
        {
            var usuario = await ObtenerUsuario();
            
                var specOrden = new OrdenConNumeroYActivaSpecification(numeroOrden);
                var ordenCorrecta = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

                
                if (ordenCorrecta != null && usuario !=null)
                {
                    var specHorarios = new HorariosDeOrdenSpecification(ordenCorrecta.Id);
                    var horarios =await _unitOfWork.Repository<HorarioTrabajo>().ListAsync(specHorarios);
                    if (horarios.Count>0)
                    {
                        var hora = _unitOfWork.GetHora();
                        var cantidad = 1;

                        ordenCorrecta.AgregarParDePrimera(hora, cantidad, usuario.Empleado,horarios);
                        await _unitOfWork.Complete();
                    }
                    
                }
                return await Iniciar(numeroOrden);
        }

        public async Task<IActionResult> RemoverParDePrimera(int numeroOrden)
        {
            var usuario = await ObtenerUsuario();
            
            var specOrden = new OrdenConNumeroYActivaSpecification(numeroOrden);
            var ordenCorrecta = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);


            if (ordenCorrecta != null && usuario != null)
            {
                var specHorarios = new HorariosDeOrdenSpecification(ordenCorrecta.Id);
                var horarios = await _unitOfWork.Repository<HorarioTrabajo>().ListAsync(specHorarios);
                if (horarios.Count > 0)
                {
                    ordenCorrecta.RemoverParDePrimera(horarios);
                    await _unitOfWork.Complete();
                }

            }
            return await Iniciar(numeroOrden);
        }

        public async Task<IActionResult> AgregarDefecto(int numeroOrden 
            , string defectoDescripcion, TipoDefecto tipoDefecto, TipoPie tipoPie)
        {
            var usuario = await ObtenerUsuario();

            var specDefecto = new DefectoDescripcionSpecification(defectoDescripcion);
            var defecto = await _unitOfWork.Repository<Defecto>().GetEntityWithSpec(specDefecto);

                var specOrden = new OrdenConNumeroYActivaSpecification(numeroOrden);
                var ordenCorrecta = await _unitOfWork.Repository<OrdenDeProduccion>()
                    .GetEntityWithSpec(specOrden);


                if (ordenCorrecta != null && usuario!= null && defecto!= null)
                {
                    var specHorarios = new HorariosDeOrdenSpecification(ordenCorrecta.Id);
                    var horarios = await _unitOfWork.Repository<HorarioTrabajo>().ListAsync(specHorarios);

                    var hora =  _unitOfWork.GetHora();
                    var cantidad =  1;
                    ordenCorrecta.AgregarDefecto(tipoPie, hora, usuario.Empleado, cantidad, defecto, horarios);
                    await _unitOfWork.Complete();
                }
                return await Iniciar(numeroOrden, defecto);
        }

        public async Task<IActionResult> RemoverDefecto(int numeroOrden
            , string defectoDescripcion, TipoDefecto tipoDefecto, TipoPie tipoPie)
        {
            var usuario = await ObtenerUsuario();

            var specDefecto = new DefectoDescripcionSpecification(defectoDescripcion);
            var defecto = await _unitOfWork.Repository<Defecto>().GetEntityWithSpec(specDefecto);

            var specOrden = new OrdenConNumeroYActivaSpecification(numeroOrden);
            var ordenCorrecta = await _unitOfWork.Repository<OrdenDeProduccion>()
                .GetEntityWithSpec(specOrden);


            if (ordenCorrecta != null && usuario != null && defecto != null)
            {
                var specHorarios = new HorariosDeOrdenSpecification(ordenCorrecta.Id);
                var horarios = await _unitOfWork.Repository<HorarioTrabajo>().ListAsync(specHorarios);

                var specHallazgos = new DefectosOrdenSpecification(horarios.Last().Id);
                var hallazgos = await _unitOfWork.Repository<Hallazgo>().ListAsync(specHallazgos);

                var hora = _unitOfWork.GetHora();
                var cantidad = 1;
                ordenCorrecta.RemoverDefecto(tipoPie, usuario.Empleado, defecto, horarios, hallazgos);
                await _unitOfWork.Complete();
            }
            return await Iniciar(numeroOrden,defecto);
        }
    }
}

CC2021/CC2021Proyecto/Views/Asociar/IniciarAsociacion.cshtml
@model IReadOnlyList<Dominio.Entities.OrdenDeProduccion>
<div class="d-flex">
    <div class='bg-primary' style='height: 91.3vh'>
        
    </div>

    <!--App-->
    <div class="container text-center">
        <h2 class='my-4' style="color: floralwhite">Ordenes de producción</h2>
        <div class="d-flex flex-column my-2">

            <!--<div class="container border border-primary overflow-auto" style="height: 60vh; width: 100vw">-->
            <table class="table table-striped" style="color: floralwhite">
                <thead>
                    <tr>
                        <th scope="col">Numero de linea</th>
                        <th scope="col">Numero de orden</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Color</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Supervisor calidad </th>
                        <th scope="col">Asociar</th>
                        <th scope="col">Desasociar</th>
                        <th scope="col">Inspeccionar</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var orden in @Model)
                    {
                        if (@Model.Count > 0)
                        {
                    <tr >
                        <th scope="row" style="vertical-align: middle;">@orden.Linea.Numero</th>
                        <td style="vertical-align: middle;">@orden.Numero</td>
                        <td style="vertical-align: middle;">@orden.Modelo.Denominacion</td>
                        <td style="vertical-align: middle;">@orden.Color.Descripcion</td>
                        <td style="vertical-align: middle;">@orden.Estado</td>
                        @if (orden.EmpleadoOrden == null)
                        {
                            <td style="vertical-align: middle;">No asignado</td>
                        }
                        else
                        {
                            <td style="vertical-align: middle;">@orden.EmpleadoOrden.Nombre @orden.EmpleadoOrden.Apellido</td>
                        }
                        <td>
                            <form asp-controller="Asociar"
                                  asp-action="AsociarSupervisor"
                                  asp-route-numeroOrden="@orden.Numero"
                                  method="post">
                                <button disabled="@(orden.EmpleadoOrden != null ? "disabled" : null)"
                                        class="btn btn-success btn-sm">

                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-box-arrow-in-up" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z" />
                                        <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                        <td>
                            <form asp-controller="Asociar"
                                  asp-action="DesasociarSupervisor"
                                  asp-route-numeroOrden="@orden.Numero"
                                  method="post">
                                <button disabled="@(orden.EmpleadoOrden == null ? "disabled" : null)" class="btn btn-danger btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-in-down" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z" />
                                        <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                        <td>
                            <form asp-controller="ControlCalidad"
                                  asp-action="IniciarInspeccion"
                                  asp-route-numeroOrden="@orden.Numero">
                            <button disabled="@(orden.EmpleadoOrden == null ? "disabled" : null)">

                                <svg height="35" viewBox="0 0 64 64" width="35" xmlns="http://www.w3.org/2000/svg"><path d="m11 22a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-4.75l4.6-3.45-1.2-1.6-3.92 2.94a.971.971 0 0 0 -.48-.14zm3.6 4.8 1.4-1.05v2.25h-4v-4h3l-1.6 1.2z"/><path d="m17.48 34.14a.971.971 0 0 0 -.48-.14h-6a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-4.75l4.6-3.45-1.2-1.6zm-1.48 5.86h-4v-4h3l-1.6 1.2 1.2 1.6 1.4-1.05z"/><path d="m21.4 43.2-3.92 2.94a.971.971 0 0 0 -.48-.14h-6a1 1 0 0 0 -1 1v6a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-4.75l4.6-3.45zm-5.4 8.8h-4v-4h3l-1.6 1.2 1.2 1.6 1.4-1.05z"/><path d="m26 20h14v2h-14z"/><path d="m26 26h14v2h-14z"/><path d="m26 32h10v2h-10z"/><path d="m26 38h4v2h-4z"/><path d="m62.092 17.737-2.829-2.829a1 1 0 0 0 -1.414 0l-9.849 9.849v-13.757a3 3 0 0 0 -3-3h-9v-1a1 1 0 0 0 -1-1h-4v-3a1 1 0 0 0 -1-1h-10a1 1 0 0 0 -1 1v3h-4a1 1 0 0 0 -1 1v1h-9a3 3 0 0 0 -3 3v48a3 3 0 0 0 3 3h40a3 3 0 0 0 3-3v-25.757l14.092-14.092a1 1 0 0 0 0-1.414zm-28.992 27.577-1.414-1.414 23.335-23.335 1.414 1.414zm-2.63.2 1.017 1.017-2.543 1.526zm14.53-35.514a1 1 0 0 1 1 1v15.757l-2 2v-15.757a1 1 0 0 0 -1-1h-7v-2zm-24-6h8v2h-8zm-5 4h18v6h-18zm19 8a1 1 0 0 0 1-1v-1h6v16.757l-12.435 12.435a1 1 0 0 0 -.15.193l-4.243 7.071a.993.993 0 0 0 .828 1.509v.035h14v-2h-10.409l4.024-2.415a1 1 0 0 0 .193-.15l8.192-8.192v16.757h-34v-42h6v1a1 1 0 0 0 1 1zm11 43a1 1 0 0 1 -1 1h-40a1 1 0 0 1 -1-1v-48a1 1 0 0 1 1-1h9v2h-7a1 1 0 0 0 -1 1v44a1 1 0 0 0 1 1h36a1 1 0 0 0 1-1v-19.757l2-2zm11.849-38.435-1.414-1.414 2.121-2.122 1.415 1.415z"/></svg>
                            </button>
                            </form>
                        </td>
                    </tr>
                        }
                    }
                </tbody>
            </table>
            <!--</div>-->
        </div>
    </div>

</div>