CC2021/CC2021Proyecto/Controllers/AsociarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using API.Specifications;
using Dominio.Entities;
using Dominio.Entities.Enums;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CC2021Proyecto.Controllers
{
    public class AsociarController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AsociarController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> IniciarAsociacion()
        {
            var spec = new OrdenesConOrdenActivaYPausadaSpecification();
            var ordenes = await _unitOfWork.Repository<OrdenDeProduccion>().ListAsync(spec);

            if (ordenes != null)
            {
                return View(ordenes);
            }

            return View();
        }

        public async Task<IActionResult> AsociarSupervisor(int numeroOrden)
        {

            var usuario = await ObtenerUsuario();

            var specOrden = new OrdenConEstadoActivaOPausadaYNumero(numeroOrden);
            var orden = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);

            var specLineas = new AddLineasIncludesSpecification();
            var lineas = await _unitOfWork.Repository<LineaDeTrabajo>().ListAsync(specLineas);

            var supervisorValido = 0;
            var hayActivasOPausadas = 0;

            if (orden != null && usuario.Empleado != null && lineas != null)
            {
                foreach (var linea in lineas)
                {
                    if (linea.OrdenesDeProduccion.All(o => o.Estado == EstadoOrden.Finalizada)) {}
                    else
                    {
                        hayActivasOPausadas++;
                        var supervisorDispo = linea.ValidarSupervisor(usuario.Empleado);
                        if (supervisorDispo)
                        {
                            supervisorValido++;
                        }
                    }
                    
                }

                if (supervisorValido == hayActivasOPausadas)
                {
                    orden.AsociarSupervisor(usuario.Empleado);
                    await _unitOfWork.Complete();
                }
            }

            return RedirectToAction("IniciarAsociacion");
        }
        public async Task<IActionResult> DesasociarSupervisor(int numeroOrden)
        {
            var usuario = await ObtenerUsuario();

            var specOrden = new OrdenConEstadoActivaOPausadaYNumero(numeroOrden);
            var orden = await _unitOfWork.Repository<OrdenDeProduccion>().GetEntityWithSpec(specOrden);


            if (orden != null && usuario.Empleado != null )
            {
                orden.DesasociarSupervisor(usuario.Empleado);
                await _unitOfWork.Complete();
                
            }
            return RedirectToAction("IniciarAsociacion");
        }
        private async Task<Usuario> ObtenerUsuario()
        {
            var sessionUser = JsonConvert.DeserializeObject<Usuario>(HttpContext.Session.GetString("SessionUser"));
            var specUsuario = new ValidarEmpleadoSpecification(sessionUser.User);
            var usuario = await _unitOfWork.Repository<Usuario>().GetEntityWithSpec(specUsuario);

            return usuario;
        }
    }
}

CC2021/CC2021Proyecto/Controllers/ColoresController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using API.Specifications;
using CC2021Proyecto.ValidationClass;
using CC2021Proyecto.ViewModels;
using Datos.Data.Interfaces;
using Dominio.Entities;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CC2021Proyecto.Controllers
{
    public class ColoresController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ColoresController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var colores = await _unitOfWork.Repository<Color>().ListAllAsync();
            var usuario = await ObtenerUsuario();
            if (usuario == null)
            {
                return RedirectToAction("ErrorAlAutenticar", "Usuarios");
            }
            return View(MapViewModel(colores, usuario));
        }

        [HttpPost]
        public async Task<ActionResult> List(string filtro)
        {
            var colores = await _unitOfWork.Repository<Color>().ListAllAsync();
            var usuario = await ObtenerUsuario();
            if (!string.IsNullOrEmpty(filtro))
            {
                var spec = new ColoresConFiltroSpecification(filtro);
                colores = await _unitOfWork.Repository<Color>().ListAsync(spec);
            }
            return View(MapViewModel(colores, usuario));
        }
        private async Task<Usuario> ObtenerUsuario()
        {
            var usuarioSesion = HttpContext.Session.GetString("SessionUser");
            if (!string.IsNullOrEmpty(usuarioSesion))
            {
                var sessionUser = JsonConvert.DeserializeObject<Usuario>(usuarioSesion);

                var specUsuario = new ValidarEmpleadoSpecification(sessionUser.User);
                var usuario = await _unitOfWork.Repository<Usuario>().GetEntityWithSpec(specUsuario);

                return usuario;
            }

            return null;

        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(ColorValidation colorValidation)
        {
            if (colorValidation == null) return BadRequest(404);
            if (ModelState.IsValid)
            {
                var color = new Color
                {
                    Codigo = colorValidation.Codigo,
                    Descripcion = colorValidation.Descripcion
                };

                var spec = new ColorConNumeroSpecification(color.Codigo);
                var colorValido = await _unitOfWork.Repository<Color>().GetEntityWithSpec(spec);
                if (colorValido == null)
                {
                    _unitOfWork.Repository<Color>().Add(color);
                    await _unitOfWork.Complete();
                    _unitOfWork.Dispose();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("","El codigo ya existe, ingrese uno nuevo");
            }
            return View();
            
        }

        public async Task<IActionResult> Edit(int codigoColor)
        {
            if (ModelState.IsValid)
            {
                var spec = new ColorConNumeroSpecification(codigoColor);
                var colorValido = await _unitOfWork.Repository<Color>().GetEntityWithSpec(spec);
                if (colorValido != null)
                {
                    var colorValidation = new ColorValidation
                    {
                        Codigo = colorValido.Codigo,
                        Descripcion = colorValido.Descripcion
                    };
                    return View(colorValidation);
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(ColorValidation colorValidation)
        {
            if (colorValidation == null) return BadRequest(404);
            if (ModelState.IsValid)
            {
                var color = new Color
                {
                    Codigo = colorValidation.Codigo,
                    Descripcion = colorValidation.Descripcion
                };

                var spec = new ColorConNumeroSpecification(color.Codigo);
                var colorValido = await _unitOfWork.Repository<Color>().GetEntityWithSpec(spec);
                if (colorValido != null)
                {
                    colorValido.Codigo = color.Codigo;
                    colorValido.Descripcion = color.Descripcion;
                    _unitOfWork.Repository<Color>().Update(colorValido);
                    await _unitOfWork.Complete();
                    _unitOfWork.Dispose();
                    return RedirectToAction("Index");
                }
                
            }
            return RedirectToAction("Edit");
        }

        public async Task<IActionResult> Delete(int codigoColor)
        {
            if (ModelState.IsValid)
            {
                var spec = new ColorConNumeroSpecification(codigoColor);
                var colorValido = await _unitOfWork.Repository<Color>().GetEntityWithSpec(spec);
                if (colorValido != null)
                {
                    _unitOfWork.Repository<Color>().Delete(colorValido);
                    await _unitOfWork.Complete();
                }
            }
            return RedirectToAction("Index");
        }

        private static ColoresListViewModel MapViewModel(IReadOnlyList<Color> colores, Usuario usuario)
        {
            if (usuario != null && colores!=null)
            {
                return new ColoresListViewModel
                {
                    Colores = colores,
                    Usuario = usuario
                };
            }
            return new ColoresListViewModel();
        }
    }
}

CC2021/CC2021Proyecto/Controllers/ModelosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using API.Specifications;
using CC2021Proyecto.ValidationClass;
using CC2021Proyecto.ViewModels;
using Dominio.Entities;
using Dominio.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CC2021Proyecto.Controllers
{
    public class ModelosController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ModelosController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var modelos = await _unitOfWork.Repository<Modelo>().ListAllAsync();
            return View(MapViewModel(modelos));
        }

        [HttpPost]
        public async Task<ActionResult> List(string filtro)
        {
            var modelos = await _unitOfWork.Repository<Modelo>().ListAllAsync(); ;
            if (!string.IsNullOrEmpty(filtro))
            {
                var spec = new ModelosConFiltroSpecification(filtro);
                modelos = await _unitOfWork.Repository<Modelo>().ListAsync(spec);

                return View(MapViewModel(modelos));
            }


            return View(MapViewModel(modelos));
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(ModeloValidation modeloValidation)
        {
            if (modeloValidation == null) return BadRequest(404);
            if (ModelState.IsValid)
            {
                var modelo = new Modelo
                {
                    Sku = modeloValidation.Sku,
                    Denominacion = modeloValidation.Denominacion,
                    Objetivo = modeloValidation.Objetivo
                };

                var spec = new ModeloConNumeroSpecification(modeloValidation.Sku);
                var modeloValido = await _unitOfWork.Repository<Modelo>().GetEntityWithSpec(spec);
                if (modeloValido == null)
                {
                    _unitOfWork.Repository<Modelo>().Add(modelo);
                    await _unitOfWork.Complete();
                    _unitOfWork.Dispose();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "El codigo ya existe, ingrese uno nuevo");
            }
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Edit(string sku)
        {
            if (ModelState.IsValid)
            {
                var spec = new ModeloConNumeroSpecification(sku);
                var modeloValido = await _unitOfWork.Repository<Modelo>().GetEntityWithSpec(spec);
                if (modeloValido != null)
                {
                    var modeloValidation = new ModeloValidation()
                    {
                        Sku = modeloValido.Sku,
                        Denominacion = modeloValido.Denominacion,
                        Objetivo = modeloValido.Objetivo
                    };
                    return View(modeloValidation);
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(ModeloValidation modeloValidation)
        {
            if (modeloValidation == null) return BadRequest(404);
            if (ModelState.IsValid)
            {
                var modelo = new Modelo
                {
                    Sku = modeloValidation.Sku,
                    Denominacion = modeloValidation.Denominacion,
                    Objetivo = modeloValidation.Objetivo
                };

                var spec = new ModeloConNumeroSpecification(modelo.Sku);
                var modeloValido = await _unitOfWork.Repository<Modelo>().GetEntityWithSpec(spec);
                if (modeloValido != null)
                {
                    modeloValido.Sku = modelo.Sku;
                    modeloValido.Denominacion = modelo.Denominacion;
                    modeloValido.Objetivo = modelo.Objetivo;
                    _unitOfWork.Repository<Modelo>().Update(modeloValido);
                    await _unitOfWork.Complete();
                    _unitOfWork.Dispose();
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Edit");
        }

        public async Task<IActionResult> Delete(string sku)
        {
            if (ModelState.IsValid)
            {
                var spec = new ModeloConNumeroSpecification(sku);
                var modeloValido = await _unitOfWork.Repository<Modelo>().GetEntityWithSpec(spec);
                if (modeloValido != null)
                {
                    _unitOfWork.Repository<Modelo>().Delete(modeloValido);
                    await _unitOfWork.Complete();
                }
            }
            return RedirectToAction("Index");
        }

        private static ModelosListViewModel MapViewModel(IReadOnlyList<Modelo> modelos)
        {
            return new ModelosListViewModel
            {
                Modelos = modelos
            };
        }
    }
}

CC2021/CC2021Proyecto/Views/Shared/ErrorGenerico.cshtml
<div class="container"  style="color:floralwhite">
    <h3  style="color:floralwhite">
        Ocurro un error procesando su solicitud
    </h3>
    <br/>
    <h3 >Detalles</h3>
    <div class="alert alert-danger"  style="color:floralwhite">
        <h5>Ruta de la excepcion</h5>
        <hr/>
        <p>@ViewBag.ExceptionPath</p>
    </div>

    <div class="alert alert-danger">
        <h5>Mensaje de error</h5>
        <hr />
        <p>@ViewBag.ExceptionMessage</p>
    </div>

    <div class="alert alert-danger">
        <h5>Pila</h5>
        <hr />
        <p>@ViewBag.StackTrace</p>
    </div>
</div>

CC2021/CC2021Proyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!--CSS-->
    
    <!--BS-->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
</head>
<body style="background: #16222A; background: -webkit-linear-gradient(to top, #3A6073, #16222A); background: linear-gradient(to top, #3A6073, #16222A);
                                  height: 100vh">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <span class="navbar-brand">Control de calidad</span>
    </div>
</nav>
<div >
    @RenderBody()
</div>
<!--SCRIPTS-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

@RenderSection("Scripts",required:false)

CC2021/CC2021Proyecto/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!--CSS-->
    <!--BS-->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <span class="navbar-brand">Control de calidad</span>
        </div>
    </nav>
    <div class="d-flex" style="background: #16222A; background: -webkit-linear-gradient(to top, #3A6073, #16222A); background: linear-gradient(to top, #3A6073, #16222A);">
        <div class='bg-primary' style='height: 90.1vh'>
            <nav>
                <div class="container border-bottom border-light py-2">
                    <h5><a asp-controller="Modelos" asp-action="Index" class='nav-item text-decoration-none text-light'>Modelos</a></h5>
                </div>
                <div class="container border-bottom border-light py-2">
                    <h5><a asp-controller="Colores" asp-action="Index" class='nav-item text-decoration-none text-light'>Colores</a></h5>
                </div>
                <div class="container border-bottom border-light py-2">
                    <h5><a class='nav-item text-decoration-none text-light'>Usuarios</a></h5>
                </div>
                <div class="container border-bottom border-light py-2">
                    <h5><a asp-controller="Usuarios" asp-action="CerrarSesion" class='nav-item text-decoration-none text-light'>Cerrar Sesion</a></h5>
                </div>
            </nav>
        </div>
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <!--SCRIPTS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

@RenderSection("Scripts",required:false)

CC2021/CC2021Proyecto/Views/Shared/_LayoutControlCalidad.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!--CSS-->
    <!--BS-->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">


</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <span class="navbar-brand">Control de calidad</span>
    </div>
</nav>
<div class="d-flex" style="background: #16222A; background: -webkit-linear-gradient(to top, #3A6073, #16222A); background: linear-gradient(to top, #3A6073, #16222A);">
    <div class='bg-primary' style='height: 90.1vh'>
        <nav>
            <div class="container border-bottom border-light py-2">
                <h5><a asp-controller="Asociar" asp-action="IniciarAsociacion" class='nav-item text-decoration-none text-light'>Administrar ordenes</a></h5>
            </div>
            <div class="container border-bottom border-light py-2">
                <h5><a asp-controller="Usuarios" asp-action="CerrarSesion" class='nav-item text-decoration-none text-light'>Cerrar Sesion</a></h5>
            </div>
        </nav>
    </div>
    <div class="container">
        @RenderBody()
    </div>
</div>
<!--SCRIPTS-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

@RenderSection("Scripts", required:false)

CC2021/CC2021Proyecto/Views/Shared/_LayoutOrden.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!--CSS-->
    <!--BS-->
    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <span class="navbar-brand">Control de calidad</span>
        </div>
    </nav>
    <div class="d-flex" style="background: #16222A; background: -webkit-linear-gradient(to top, #3A6073, #16222A); background: linear-gradient(to top, #3A6073, #16222A);">
        <div class='bg-primary' style='height: 90.1vh'>
            <nav>
                <div class="container border-bottom border-light py-2">
                    <h5><a asp-controller="OrdenDeProduccion" asp-action="ObtenerLineas" class='nav-item text-decoration-none text-light'>Administrar ordenes</a></h5>
                </div>
                <div class="container border-bottom border-light py-2">
                    <h5><a asp-controller="Usuarios" asp-action="CerrarSesion" class='nav-item text-decoration-none text-light'>Cerrar Sesion</a></h5>
                </div>
            </nav>
        </div>
        <div class="container">
            @RenderBody()
        </div>
    </div>
    <!--SCRIPTS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

@RenderSection("Scripts", required: false)